
# _config.yml
# baseurl: "/urbarSolivar"
url: "https://www.urbar-solivar.sk"

# Name of website
title: Urbár Solivar pozem. spol.

#Language
lang: sk

# Your name to show in the footer
author: Urbár Solivar, Na vyhliadke 6, 080 05 Prešov
###############################################
# --- List of links in the navigation bar --- #
###############################################
# Tags
tag_dir: tag

# Remove Ads

remove-ads: True

navbar-links:
  O nás: "about"
  Informácie:
    - Organizačná štruktúra: "organization"
    - Dokumenty: "docs"
    - Registrácia spoločenstva: "about"
    - Finančné ukazovatele: "https://finstat.sk/42382742"
    - História: "historia"
  Kontakty: "contacts"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/solivar-2.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/custom-styles.css"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"


# Fill in your Google Analytics tag ID (or "Measurement ID") to track your website usage
gtag: "G-EG5J9K5M2B"


#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Europe/Bratislava"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/


kramdown:
  input: GFM

date_format: "%d. %m. %Y"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"


# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: Rss Urbár Solivar pozem. spol.

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "urbar.solivar@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "urbar-solivar.sk"

# Add the website title to the title of every page
title-on-all-pages: true  

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

  
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png


plugins:
  - jekyll-remote-theme
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship
  - jekyll-admin
  - jekyll-sitemap

remote_theme: daattali/beautiful-jekyll@6.0.1 
