backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: urbar-solivar/urbarSolivar 
  base_url: https://urbar-solivar-auth-aq6ze6ja7-imcontec.vercel.app
  auth_endpoint: /api/auth
  
media_folder: 'assets/uploads'

collections:
  - name: 'oznamy'
    label: 'Oznamy'
    folder: '_posts/'
    create: true # Umožní zákazníkovi pridať nový príspevok
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formát názvu súboru
    extension: "md"
    summary: "📅 {{date | date('D.M.YYYY')}} | ✍️ {{author}} | {{title}} |"
    sortable_fields: ['date', 'title'] # Povolené polia na triedenie v UI
    sort: { field: 'date', direction: 'descending' } # Predvolené triedenie: od najnovšieho
    fields:
      - { label: "Názov", name: "title", widget: "string" }
      - { label: "Publikované", name: "published", widget: "boolean", default: true }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "{{user.name}}" }
      - { label: "Kategórie", name: "categories", widget: "string" }
      - { label: "Tagy", name: "tags", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Obsah", name: "body", widget: "markdown" }
      
